//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAccounting.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publishers
    {
        public int PublisherId { get; set; }
        public string PublisherName { get; set; }
        public string City { get; set; }
    }
}
