//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAccounting.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rows()
        {
            this.BookCopies = new HashSet<BookCopies>();
        }
    
        public int RowId { get; set; }
        public int RowNumber { get; set; }
        public int ShelfId { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public int Capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookCopies> BookCopies { get; set; }
        public virtual Shelves Shelves { get; set; }
    }
}
